### PR TITLE
updated v6.4.0

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/octave-feedstock/pull/57
Closes https://github.com/conda-forge/octave-feedstock/pull/59
Closes https://github.com/conda-forge/octave-feedstock/pull/61
Closes https://github.com/conda-forge/octave-feedstock/pull/63

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by ngam** [comment]
hmmm

**Comment by ngam** [comment]
where exactly do we give it sundials?

```
checking for SUNDenseLinearSolver... no
checking whether SUNDIALS API provides the necessary functions... yes
checking whether SUNDIALS IDA is configured with double precision realtype... yes
checking sunlinsol/sunlinsol_dense.h usability... ye
```

**Comment by izahn** [comment]
> where exactly do we give it sundials?
> 
> ```
> checking for SUNDenseLinearSolver... no
> checking whether SUNDIALS API provides the necessary functions... yes
> checking whether SUNDIALS IDA is configured with double precision realtype... yes
> checking sunlinsol/sunlinsol_dense.h usability... ye
> ```

https://github.com/izahn/octave-feedstock/blob/50d6cbeb3588919bb3d98c308c4e251d0a07f9b2/recipe/meta.yaml#L53

**Comment by ngam** [comment]
> > where exactly do we give it sundials?
> > ```
> > checking for SUNDenseLinearSolver... no
> > checking whether SUNDIALS API provides the necessary functions... yes
> > checking whether SUNDIALS IDA is configured with double precision realtype... yes
> > checking sunlinsol/sunlinsol_dense.h usability... ye
> > ```
> 
> https://github.com/izahn/octave-feedstock/blob/50d6cbeb3588919bb3d98c308c4e251d0a07f9b2/recipe/meta.yaml#L53

Okay, testing locally. Please lower sundials. Goes much farther than this.

**Comment by ngam** [comment]
I cannot recommend changes... but as a first swipe, please go for `<6` both runtime and host

**Comment by ngam** [comment]
I sorta believe this is it. I am kinda confused why sundials isn't pinned globally though...

**Comment by ngam** [comment]
Okay, got this error for sundials 5.7.x on osx

```
      void std::__1::vector<Magick::ColorRGB, std::__1::allocator<Magick::ColorRGB> >::__push_back_slow_path<Magick::ColorRGB>(Magick::ColorRGB&&) in libcorefcn.a(libcorefcn_la-__magick_read__.o)
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64

```

waiting for linux run to go through with 5.8.x

should we use the new qt feedstock btw?

**Comment by izahn** [comment]
As an alternative to sticking with `sundials 5.x` we could adopt the Arch Linux patch at https://github.com/archlinux/svntogit-community/blob/packages/octave/trunk/PKGBUILD .  That would be my preference.

**Comment by ngam** [comment]
> That would be my preference

my preference, too. Please go ahead. Or do you want to give me push access to your fork?

**Comment by ngam** [comment]
archlinux patches, to the rescue, yet again! 🥳

**Comment by izahn** [comment]
OK great! The direct link to the patch is https://github.com/archlinux/svntogit-community/blob/packages/octave/trunk/octave-sundials-6.0.patch

I invited you to my fork, feel free to push there!

**Comment by ngam** [comment]
```
Octave successfully built.  Now choose from the following:

   ./run-octave    - to run in place to test before installing
   make check      - to run the tests
   make install    - to install (PREFIX=$PREFIX)

   HG ID for this build is "8d7671609955"
```

**Comment by ngam** [comment]
TODO: 
- [ ] add libtool

**Comment by ngam** [comment]
@izahn 

```
Mamba failed to solve:
 - octave 6.4.0.* h8594d46_0
 - _openmp_mutex >=4.5
 - alsa-lib >=1.2.3,<1.2.4.0a0
 - arpack >=3.7.0,<3.7.1.0a0
 - bzip2 >=1.0.8,<2.0a0
 - curl >=7.80.0,<8.0a0
 - fftw >=3.3.10,<4.0a0
 - fltk >=1.3.8,<1.4.0a0
 - fontconfig >=2.13.1,<3.0a0
 - fonts-conda-ecosystem
 - freetype >=2.10.4,<3.0a0
 - ghostscript
 - gl2ps >=1.4.2,<1.4.3.0a0
 - glib
 - glpk >=4.65,<4.66.0a0
 - gnuplot
 - graphicsmagick >=1.3.37,<2.0a0
 - hdf5 >=1.12.1,<1.12.2.0a0
 - icu >=68.2,<69.0a0
 - libblas >=3.8.0,<4.0a0
 - libcblas >=3.8.0,<4.0a0
 - libcurl >=7.80.0,<8.0a0
 - libgcc-ng >=9.4.0
 - libgfortran-ng
 - libgfortran5 >=9.4.0
 - libglib >=2.70.2,<3.0a0
 - libglu
 - libiconv >=1.16,<1.17.0a0
 - liblapack >=3.8.0,<4.0a0
 - liblapacke >=3.8.0,<4.0a0
 - libpng >=1.6.37,<1.7.0a0
 - libsndfile >=1.0.31,<1.1.0a0
 - libstdcxx-ng >=9.4.0
 - libxml2 >=2.9.12,<2.10.0a0
 - libzlib >=1.2.11,<1.3.0a0
 - ncurses >=6.2,<6.3.0a0
 - openssl >=1.1.1l,<1.1.2a
 - pcre >=8.45,<9.0a0
 - portaudio >=19.6.0,<20.0a0
 - qhull >=2020.2,<2020.3.0a0
 - qscintilla2 >=2.11.2,<2.12.0a0
 - qt >=5.12.9,<5.13.0a0
 - readline >=8.1,<9.0a0
 - suitesparse >=5.10.1,<5.11.0a0
 - suitesparse >=5.10.1,<6.0a0
 - sundials >=6.0.0,<6.1.0a0
 - texinfo
 - xz >=5.2.5,<5.3.0a0
 - zlib >=1.2.11,<1.3.0a0
 - coreutils

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package octave-6.4.0-h8594d46_0 requires sundials >=5.8.0,<5.9.0a0, but none of the providers can be installed
- 
```

We may need  to pin to 5.8...

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge/octave (@ocefpaf @isuruf): all green as of 3f22ad8 + added libtool two new maintainers. Please merge/automerge when ready, thanks.

Up next (future PR): try qt-main and build for osx-arm64 + address issues

**Comment by izahn** [comment]
It looks good to me!

**Comment by izahn** [comment]
This one is ready for review @conda-forge/octave

**Pull request merged**
