### PR TITLE
icu70 migration

### PR DESCRIPTION
**Pull request by ngam**
there was an error elsewhere causing the bot to give up. Trying manually. Should go through after some CI issues are fixed in https://github.com/conda-forge/xerces-c-feedstock/pull/32

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
rerun in a few hours...

**Comment by izahn** [comment]
Since `qt=51.2` was never migrated to `icu70` the `icu70` migration here needs `qt-main`, as you already figured out. Unfortunately the `qt-main` migration depends on migrating `qscintilla2` first. I started working on that in https://github.com/conda-forge/qscintilla2-feedstock/pull/40, though I'm not 100% sure I'm on the right track there.

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by izahn** [comment]
Looks good!

**Comment by ngam** [comment]
Do the honors of you feel like it!

**Pull request merged**
